### ISSUE TITLE
Why an amount could be null?

### ISSUE THREAD

**Issue by michelcedric** [wl-online-payments-direct/sdk-dotnet#5]
Hi
I not understand why a payment could be have a null amount?
https://github.com/wl-online-payments-direct/sdk-dotnet/blob/master/OnlinePayments.Sdk/Domain/AmountOfMoney.cs#L11

**Comment by worldline-direct-support-team** [comment]
Hello Michel,

Thank you for your question.
The amount (and currency code) are by default initialized with null-values. However, it is up to you to set the values that you actually need for your payment. 
The examples in section 3. of [this page](https://support.direct.worldline-solutions.com/en/documentation/sdk/server/dotnet/) show how to do this.

Kind regards,
Worldline Online Payments Support

**Comment by worldline-direct-support-team** [comment]
Hi Michel,

That is correct. The amount can technically be null, but it should never be. When an `amountOfMoney` object is returned by the API, the `amount` and `currencyCode` will always be set. And when providing an `amountOfMoney` object, they both need to be set. The server will not accept null values.

Kind regards,
Worldline Online Payments Support
